updating repo

diff --git a/foulab-driving-me/bin/make_pm_pmlab b/foulab-driving-me/bin/make_pm_pmlab
--- a/foulab-driving-me/bin/make_pm_pmlab
+++ b/foulab-driving-me/bin/make_pm_pmlab
@@ -1,4 +1,5 @@
-########################################################-*-mode:Makefile-*-
+#!/bin/sh
+#####################################################-*-mode:shell-script-*-
 ##                                                                       ##
 ##                   Carnegie Mellon University and                      ##
 ##                   Alan W Black and Kevin A. Lenzo                     ##
@@ -30,40 +31,47 @@
 ##  THIS SOFTWARE.                                                       ##
 ##                                                                       ##
 ###########################################################################
-##                                                                       ##
-##    User defined configuration options                                 ##
-##                                                                       ##
+###                                                                      ##
+###  Generate EST pm label format from xlabel format                     ##
+###  used for putting back edited pm files                               ##
+###                                                                      ##
 ###########################################################################
 
-###########################################################################
-##  The location of your compiled speech_tools.                          ##
-##                                                                       ##
-##  Unless you have set LD_LIBRARY_PATH you'll find compiling the system ##
-##  not as SHARED easier                                                 ##
-###########################################################################
+LANG=C; export LANG
 
-ESTDIR=/home/s/Github/synthetic-voices/download/festvox
+if [ $# = 0 ]
+then
+   echo "Make pm from pm labels (after editing)"
+   echo "Usage:  bin/make_pm_pmlab pm_lab/*.lab"
+   echo "Will overwrite pm/*.pm"
+   exit 1
+fi
 
-###########################################################################
-##  The location of your compiled Festival (2.0)                         ##
-###########################################################################
+if [ `dirname $1` = "pm" ]
+then
+   echo 
+   echo "ERROR"
+   echo "This function generates pm from pmlab files.  "
+   echo "you probably wanted to type "
+   echo "      bin/make_pm_pmlab pm_lab/*.lab"
+   echo "not"
+   echo "      bin/make_pm_pmlab pm/*.pm"
+   echo
+   exit
+fi
 
-FESTDIR=$(ESTDIR)/../festival
-
-###########################################################################
-##  General flags (note something inherit their flags from EST directly  ##
-###########################################################################
-
-CC       = gcc
-CFLAGS   = -g -O2 -Wall
-CPPFLAGS = 
-SHFLAGS  = 
-NOPTHREADFLAGS  = 
-
-AR       = ar
-RANLIB   = ranlib
-INSTALL  = /usr/bin/install -c
-
-
-
-
+for i in $*
+do
+   fname=`basename $i .lab`
+   echo $fname
+   echo "EST_File Track" >pm/$fname.pm
+   echo "DataType ascii" >>pm/$fname.pm
+   echo "NumFrames" `awk '{if ($1 == "#") t=NR} END {print NR-t}' $i` >>pm/$fname.pm
+   echo "NumChannels 0" >>pm/$fname.pm
+   echo "NumAuxChannels 0" >>pm/$fname.pm
+   echo "EqualSpace 0" >>pm/$fname.pm
+   echo "BreaksPresent true" >>pm/$fname.pm
+   echo "file_type 13" >>pm/$fname.pm
+   echo "EST_Header_End" >>pm/$fname.pm
+   awk '{if (NF == 3) printf("%f 1\n",$1)}' <$i >>pm/$fname.pm
+done
diff --git a/foulab-driving-me/bin/make_pmlab_pm b/foulab-driving-me/bin/make_pmlab_pm
--- a/foulab-driving-me/bin/make_pmlab_pm
+++ b/foulab-driving-me/bin/make_pmlab_pm
@@ -1,4 +1,5 @@
-########################################################-*-mode:Makefile-*-
+#!/bin/sh
+#####################################################-*-mode:shell-script-*-
 ##                                                                       ##
 ##                   Carnegie Mellon University and                      ##
 ##                   Alan W Black and Kevin A. Lenzo                     ##
@@ -31,39 +32,45 @@
 ##                                                                       ##
 ###########################################################################
 ##                                                                       ##
-##    User defined configuration options                                 ##
+##  Generate xlabel format representation of EST pm files suitable       ##
+##  for view in University of Macquarie's emulabel or Entropic's Xwaves  ##
 ##                                                                       ##
 ###########################################################################
 
-###########################################################################
-##  The location of your compiled speech_tools.                          ##
-##                                                                       ##
-##  Unless you have set LD_LIBRARY_PATH you'll find compiling the system ##
-##  not as SHARED easier                                                 ##
-###########################################################################
+LANG=C; export LANG
 
-ESTDIR=/home/s/Github/synthetic-voices/download/festvox
+if [ $# = 0 ]
+then
+   echo "Make pm labels for viewing in emulabel or similar"
+   echo "Usage:  bin/make_pmlab_pm pm/*.pm"
+   echo "Will create pm_lab/*.lab"
+   exit 1
+fi
 
-###########################################################################
-##  The location of your compiled Festival (2.0)                         ##
-###########################################################################
+if [ `dirname $1` = "pm_lab" ]
+then
+   echo 
+   echo "ERROR"
+   echo "This function generates pmlab from pm files.  "
+   echo "you probably wanted to type "
+   echo "      bin/make_pmlab_pm pm/*.pm"
+   echo "not"
+   echo "      bin/make_pmlab_pm pm_lab/*.lab"
+   echo
+   exit
+fi
 
-FESTDIR=$(ESTDIR)/../festival
-
-###########################################################################
-##  General flags (note something inherit their flags from EST directly  ##
-###########################################################################
-
-CC       = gcc
-CFLAGS   = -g -O2 -Wall
-CPPFLAGS = 
-SHFLAGS  = 
-NOPTHREADFLAGS  = 
-
-AR       = ar
-RANLIB   = ranlib
-INSTALL  = /usr/bin/install -c
-
-
-
-
+for i in $* 
+do
+   echo $i
+   fname=`basename $i .pm`
+   awk '{if ($1 == "EST_Header_End")
+         {
+            post_header = 1;
+            printf("#\n");
+         }
+         else if (post_header == 1)
+         {
+	     printf("%f 125 %f\n",$1,$2);
+         }}' $i >pm_lab/$fname.lab
+done
